In [1]:
# 1. Load the dataset into Python using pandas
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(r"employee_attrition(random forest).csv")
df.head()

,Age,Department,Years_At_Company,Salary,Overtime,JobSatisfaction,Attrition
0,29,Sales,12,38,No,3,No
1,23,Finance,12,98,No,1,Yes
2,39,Tech,19,46,No,1,No
3,37,Finance,14,46,No,5,Yes
4,36,Tech,16,90,No,4,Yes

In [2]:
#2. Display the first 5 rows and describe each feature.
df.describe()

            Age  Years_At_Company      Salary  JobSatisfaction
count  50.00000          50.00000   50.000000        50.000000
mean   35.22000          10.20000   65.340000         3.080000
std     8.78842           6.38557   22.293598         1.626816
min    22.00000           0.00000   30.000000         1.000000
25%    27.25000           5.00000   46.000000         1.250000
50%    35.50000          10.00000   60.500000         3.000000
75%    42.25000          16.00000   86.750000         5.000000
max    54.00000          20.00000  100.000000         5.000000

In [3]:
#3. Check for missing values and handle them if any.
df.isnull().sum()

Age                 0
Department          0
Years_At_Company    0
Salary              0
Overtime            0
JobSatisfaction     0
Attrition           0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
#4. Convert categorical variables (Department, Overtime) into numerical form.
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])
df.head()

,Age,Department,Years_At_Company,Salary,Overtime,JobSatisfaction,Attrition
0,29,2,12,38,0,3,0
1,23,0,12,98,0,1,1
2,39,3,19,46,0,1,0
3,37,0,14,46,0,5,1
4,36,3,16,90,0,4,1

In [6]:
#5. Split the dataset into features (X) and target (y).
X=df.iloc[:,:-1]
y=df["Attrition"]

In [7]:
#6. Perform train-test split (70% train, 30% test).
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42,stratify=y)

In [8]:
#7. Train a Random Forest Classifier on the training set.
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [9]:
#8. Print the number of trees and features used in training.
print("Number of trees:", rf.n_estimators)
print("Number of features:", X_train.shape[1])

Number of trees: 100
Number of features: 6

In [10]:
#9. Predict on the test set.
y_pred = rf.predict(X_test)

In [11]:
#10. Evaluate performance using accuracy, confusion matrix, and classification report.

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.4666666666666667
Confusion Matrix:
 [[5 2]
 [6 2]]
Classification Report:
               precision    recall  f1-score   support

           0       0.45      0.71      0.56         7
           1       0.50      0.25      0.33         8

    accuracy                           0.47        15
   macro avg       0.48      0.48      0.44        15
weighted avg       0.48      0.47      0.44        15

In [12]:
#11. Experiment with n_estimators, max_depth, and criterion. Compare results.
# Example tuning
rf_tuned = RandomForestClassifier(n_estimators=200, max_depth=10, criterion="entropy", random_state=42)
rf_tuned.fit(X_train, y_train)
y_pred_tuned = rf_tuned.predict(X_test)

print("Tuned Accuracy:", accuracy_score(y_test, y_pred_tuned))

Tuned Accuracy: 0.4666666666666667

In [13]:
#12. Check feature importances and identify the most important predictors of attrition.

feature_importances = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

feature_importances.head()

            Feature  Importance
3            Salary    0.313627
0               Age    0.233029
2  Years_At_Company    0.180854
5   JobSatisfaction    0.129833
1        Department    0.112483

In [14]:
#13. Which features influence employee attrition the most?
feature_importances.head(1)

  Feature  Importance
3  Salary    0.313627

In [15]:
#14. If you were the HR manager, how would you use these insights to reduce attrition?

print ("""If I were the HR manager, I would focus on improving employee compensation and ensuring salaries are competitive, 
since pay is a major reason for attrition.
Along with financial incentives, I would also look into creating career growth opportunities,
recognition programs and work-life balance initiatives.
By addressing both salary and job satisfaction, I could reduce turnover and keep employees more engaged and motivated..""")

If I were the HR manager, I would focus on improving employee compensation and ensuring salaries are competitive,
since pay is a major reason for attrition.
Along with financial incentives, I would also look into creating career growth opportunities,
recognition programs and work-life balance initiatives.
By addressing both salary and job satisfaction, I could reduce turnover and keep employees more engaged and motivated..